spring:
  application:
    name: notes
  datasource:
    url: "jdbc:postgresql://panic-db-prod.cknyi4i083fx.us-east-1.rds.amazonaws.com:5432/panicbtn?currentSchema=public&sslmode=require&uselibpqcompat=true"
    username: ${DB_USER:postgres}
    password: "${DB_PASS:%p4n1cButt0n_?}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect